### ISSUE TITLE
Set up skips plugin metadata questions

### ISSUE THREAD

**Issue by GenoPeppino** [yootheme/starter-plugin#2]
Probably an issue on my end, but every time I run composer it skips the...
"You will be asked for additional plugin information which will be used in the plugin metadata"
...part of the set up process.
```
Creating a "yootheme/starter-plugin" project at "./test-two-plugin"
Installing yootheme/starter-plugin (1.0.2)
  - Installing yootheme/starter-plugin (1.0.2): Extracting archive
Created project in C:\Users\TstUsr\Local Sites\yooplgnlaunch\app\public\wp-content\plugins\test-two-plugin
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking yootheme/starter-utils (1.0.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing yootheme/starter-utils (1.0.6): Extracting archive
Generating autoload files
No security vulnerability advisories found
Plugin 'test_two_plugin' created successfully.
Enter plugin title:
C:\Users\TstUsr\Local Sites\yooplgnlaunch\app\public\wp-content\plugins>    
```
It doesn't actually give me the chance to "Enter plugin title", it just skips down to the dir prompt.

Any advice is welcome.

**Comment by pnkr** [comment]
I have the same issue.
I followed the steps that the documentation says but it misses all the meta data information to set

**Comment by GenoPeppino** [comment]
Still having this issue. I'm trying to install the plugin in a "Local WP" site (flywheel's dev server). I've used both the built in composer via the program's "Site Shell" and again with a separate composer install via VS Code terminal, and got the same result.

**Comment by pnkr** [comment]
> Still having this issue. I'm trying to install the plugin in a "Local WP" site (flywheel's dev server). I've used both the built in composer via the program's "Site Shell" and again with a separate composer install via VS Code terminal, and got the same result.

I used Ms VS Code and Microsoft Powershell terminal and the same thing happens. The only thing is that with Powershell at least it wrote the Enter plugin title: MyPluginName and stopped.

**Comment by hendrikbehncke** [comment]
Unfortunately wee needed to remove the interactive script from the post-create-project command because it does not work on Windows.

Closing this as duplicate of https://github.com/yootheme/starter-plugin/issues/5
