### ISSUE TITLE
Taskfile.yml Missing - Error During Post-Update Event in Composer

### ISSUE THREAD

**Issue by Taimurian** [yootheme/starter-plugin#3]
**Description**:
I'm encountering an issue when trying to create a new Yootheme starter plugin using Composer. The process fails during the post-update-cmd event with the following error:

```
Script YOOTHEME\Starter\TaskHelper::postUpdate handling the post-update-cmd event terminated with an exception

In TaskHelper.php line 126:
hash_file(build/Taskfile.yml): Failed to open stream: No such file or directory
```

It appears that the file `build/Taskfile.yml` is missing, or the path to it is incorrect, leading to the failure. This occurred while running the following command:

```bash
composer create-project yootheme/starter-plugin my-plugin
```

### Steps to Reproduce:
1. Run `composer create-project yootheme/starter-plugin my-plugin`
2. Wait for the installation process to complete.
3. Observe the error related to the missing `Taskfile.yml`.

### Expected Behavior:
The project should be created without errors, and no missing files should cause the post-update event to fail.

### Actual Behavior:
The process halts with the `hash_file(build/Taskfile.yml): Failed to open stream` error, indicating the file is not found or not generated correctly.

### Environment:
- **Composer version**: 2.7.9
- **PHP version**: 8.2.12
- **OS**: Windows 11
- **Yootheme Starter Plugin Version**: 1.0.3

### Additional Context:
I've attached a screenshot showing the full error log during the installation process. Please advise if there are any missing steps, or if the file should be generated by another process.

**Screenshot**:  

![ScreenShot_20241001080816](https://github.com/user-attachments/assets/c5285798-35be-4401-9e0b-673e6cdb1ab0)

**Comment by GeraintEdwards** [comment]
I see the same issue in Linux with 

PHP 8.1.29
Composer 2.7.9

**Comment by GeraintEdwards** [comment]
See https://github.com/yootheme/starter-utils/issues/1 for possible explanation

**Comment by dformdotdk** [comment]
Same here in MacOS Sequoia
